spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
    username: "root"
    password: "{cipher}6d41bb8a60f12aa3a60ffbbc1c2bdaf31e0d23ca851b4f2b0d65410ea48f0661"
    driver-class-name: "com.mysql.jdbc.Driver"
    dbcp2:
      test-while-idle: true
      validation-query: "SELECT 1"
      
security:
  basic:
    enabled: false
    
server:
  port: 8081
  
eureka:
   instance:
       preferIpAddress: true
   client:
       registerWithEureka: true
       fetchRegistry: true
       serviceUrl:
           defaultZone: http://localhost:8761/eureka/